gui:
  showIcons: true
  border: rounded
  theme:
    activeBorderColor:
      - "#89b4fa" # Mauve
      - bold
    inactiveBorderColor:
      - "#6c7086" # Overlay0
    searchingActiveBorderColor:
      - "#f9e2af" # Yellow
    optionsTextColor:
      - "#b4befe" # Lavender
    selectedLineBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#45475a" # Surface1
    cherryPickedCommitFgColor:
      - "#94e2d5" # Teal
    unstagedChangesColor:
      - "#f38ba8" # Red
    defaultFgColor:
      - "#cdd6f4" # Text
  authorColors:
    "*": "#b4befe"
  showFileTree: true # Toggle with '`'
  sidePanelWidth: 0.33
  mainPanelSplitMode: "vertical"
  statusPanelView: "folded"
  language: "en"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --commit-style box --line-numbers --side-by-side
  commit:
    signOff: false
  skipHookPrefix: WIP
  mainBranches: [master, main]

os:
  editCommand: "nvim"
  editCommandTemplate: "{{editor}} {{filename}}"

keybinding:
  universal:
    prevItem: "<c-p>"
    nextItem: "<c-n>"
    prevBlock: "<c-h>"
    nextBlock: "<c-l>"
    scrollUpMain: "<c-u>"
    scrollDownMain: "<c-d>"

customCommands:
  - key: "C"
    command: "git cz"
    context: "files"
    description: "commit with commitizen"
    subprocess: true
  - key: "a"
    command: "git commit --amend --no-edit"
    context: "files"
    description: "amend last commit"
    loadingText: "amending commit"
